# Angular - Frontend - CI

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli
  displayName: 'npm install @angular/cli'

- script: npm install
  displayName: 'npm install dependencies'

- script: npm run build --prod
  displayName: 'npm run build --prod'

- script: npm run lint
  displayName: 'npm run lint'

- script: npm run test
  displayName: 'npm run test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'

- script: npm audit
  displayName: 'npm audit'
  continueOnError: 'true'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'joachimveulemans/chessgame'
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: 'frontend'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'joachimveulemans/chessgame'
    command: 'build'
    Dockerfile: 'Dockerfile-documentation'
    tags: 'documentation'
